#!/usr/bin/env node
// Generated by scripts/build.cjs. Edit src/ and locale/.
const UI_CATALOGS = {
  "en": {
    "permission.reason.service": "Share one background service for hooks, agent state, bookmarks and notifications. Keep it alive for up to 10 minutes after the last window closes.",
    "service.noService": "Service unregistered: close and reopen this window",
    "service.failed": "Service connection failed; Start to retry",
    "service.serverFailed": "Port {port} failed; Start to retry",
    "nav.dashboard": "Dashboard",
    "nav.agents": "Agent State",
    "nav.activity": "Activity",
    "Claude State": "Claude State",
    " Claude Dashboard ": " Claude Dashboard ",
    "[a] Dashboard": "[a] Dashboard",
    "[h] Dashboard": "[h] Dashboard",
    "[r] Refresh": "[r] Refresh",
    "[a] Agent State": "[a] Agent State",
    "[h] Heatmap": "[h] Heatmap",
    "Back to dashboard": "Back to dashboard",
    "Loading...": "Loading...",
    "No data": "No data",
    "No credentials found": "No credentials found",
    "Claude Status: Checking...": "Claude Status: Checking...",
    "Claude Status: Unavailable": "Claude Status: Unavailable",
    "Claude Status: ": "Claude Status: ",
    "Affected: ": "Affected: ",
    "Claude Service Restored": "Claude Service Restored",
    "Claude services are operational again.": "Claude services are operational again.",
    "Plan: ": "Plan: ",
    "  Effort: ": "  Effort: ",
    "Rate Limits": "Rate Limits",
    "No rate limit data available": "No rate limit data available",
    "Extra Usage": "Extra Usage",
    " spent": " spent",
    "Remaining: ": "Remaining: ",
    "Extra usage enabled, no spend this period": "Extra usage enabled, no spend this period",
    "Failed to fetch rate limits": "Failed to fetch rate limits",
    "Check ~/.claude/.credentials.json": "Check ~/.claude/.credentials.json",
    "Session": "Session",
    "Uptime: ": "Uptime: ",
    "Updated: ": "Updated: ",
    " (cached)": " (cached)",
    "s ago": "s ago",
    " Activity Heatmap ": " Activity Heatmap ",
    "(52 weeks)": "(52 weeks)",
    "Loading heatmap data...": "Loading heatmap data...",
    "No activity data available": "No activity data available",
    "Less ": "Less ",
    " More": " More",
    "Statistics": "Statistics",
    "Active days: ": "Active days: ",
    "Sessions: ": "Sessions: ",
    "Current streak: ": "Current streak: ",
    "Longest: ": "Longest: ",
    " days": " days",
    "now": "now",
    "5-hour limit": "5-hour limit",
    "7-day limit": "7-day limit",
    "Fable weekly limit": "Fable weekly limit",
    "Stop": "Stop",
    "Start": "Start",
    "  Hook Server  ": "  Hook Server  ",
    "  Pattern Match": "  Pattern Match",
    "stopped": "stopped",
    "1.5s interval": "1.5s interval",
    "off": "off",
    "Notify": "Notify",
    "Previous preset": "Previous preset",
    "Cycle preset": "Cycle preset",
    "Next preset": "Next preset",
    "Reset to default preset": "Reset to default preset",
    "Reset": "Reset",
    "Suppress during compact": "Suppress during compact",
    " Suppress during compact": " Suppress during compact",
    "Compaction fires Stop as a side effect": "Compaction fires Stop as a side effect",
    "Terminals": "Terminals",
    "(none)": "(none)",
    "Right-click for terminal actions": "Right-click for terminal actions",
    "  compacting": "  compacting",
    "Log": "Log",
    "Clear log": "Clear log",
    "Clear": "Clear",
    "Install / update Claude Code hooks": "Install / update Claude Code hooks",
    "Stop hook server": "Stop hook server",
    "Start hook server": "Start hook server",
    "Stop pattern matching": "Stop pattern matching",
    "Start pattern matching": "Start pattern matching",
    "Reveal log file": "Reveal log file",
    "Quit": "Quit",
    "Install Claude Code Hooks": "Install Claude Code Hooks",
    "Install": "Install",
    "Cancel": "Cancel",
    "Screen-scraping fallback when hooks are unavailable": "Screen-scraping fallback when hooks are unavailable",
    "response complete": "response complete",
    "ended with an error": "ended with an error",
    "needs permission": "needs permission",
    "session started": "session started",
    "idle": "idle",
    "strict": "strict",
    "normal": "normal",
    "all": "all",
    "custom": "custom",
    "running": "running",
    "waiting": "waiting",
    "blocked": "blocked",
    "turn complete": "turn complete",
    "turn ended with error": "turn ended with error",
    "permission prompt (mid-turn)": "permission prompt (mid-turn)",
    "permission.reason.startup": "Tell you when a Claude turn finishes, when Claude stops for your approval, and when a Claude service outage is over, so you do not have to keep this dashboard in view. Notifications name the terminal and are sent only on those state changes.",
    "permission.reason.agent": "Tell you that the Claude session in the terminal being tracked has finished its turn, ended with an error, or is waiting for your approval.",
    "permission.reason.recovery": "Tell you the moment the Claude service outage shown on this dashboard is over, so you can pick your work back up.",
    "permission.notify.blocked": "notifications blocked",
    "permission.badge.blocked": "terminal badges blocked",
    "session start / resume / clear": "session start / resume / clear",
    "idle prompt after 60s": "idle prompt after 60s",
    "Mon": "Mon",
    "Wed": "Wed",
    "Fri": "Fri",
    "Sun": "Sun",
    "Token expired or invalid (401). Re-login to Claude Code.": "Token expired or invalid (401). Re-login to Claude Code.",
    "{label}\nResets: {exact}\nRemaining: {remaining}": "{label}\nResets: {exact}\nRemaining: {remaining}",
    "{port} · {count} clients": "{port} · {count} clients",
    "{action} hook server": "{action} hook server",
    "Click to {action} the hook server": "Click to {action} the hook server",
    "{action} pattern matching": "{action} pattern matching",
    "{action} {event} notification": "{action} {event} notification",
    "Enable": "Enable",
    "Disable": "Disable",
    "Allow notifications during compact": "Allow notifications during compact",
    "Suppress notifications during compact": "Suppress notifications during compact",
    "Clear badge for {name}": "Clear badge for {name}",
    "+{count} more": "+{count} more",
    "Preset: {name}": "Preset: {name}",
    "{who} — {message}": "{who} — {message}",
    "Add or update hooks in Claude Code settings.json\nto enable Claude State detection.\n\nTarget: {path}\nOut of date: {events}": "Add or update hooks in Claude Code settings.json\nto enable Claude State detection.\n\nTarget: {path}\nOut of date: {events}",
    "Network error: {error}": "Network error: {error}",
    "Failed to fetch: {error}": "Failed to fetch: {error}",
    "API error (HTTP {status})": "API error (HTTP {status})",
    "API rate limited (429). Retrying in {minutes}min...": "API rate limited (429). Retrying in {minutes}min...",
    "event.Stop": "Stop",
    "event.StopFailure": "StopFailure",
    "event.PermissionRequest": "PermissionRequest",
    "event.SessionStart": "SessionStart",
    "event.Idle": "Idle",
    "All Systems Operational": "All Systems Operational",
    "Partial System Outage": "Partial System Outage",
    "Major System Outage": "Major System Outage",
    "Minor Service Outage": "Minor Service Outage",
    "Degraded System Service": "Degraded System Service",
    "DOWN": "DOWN",
    "Request failed": "Request failed",
    "unknown": "unknown",
    "{count}d": "{count}d",
    "{count}h": "{count}h",
    "{count}m": "{count}m",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec",
    "Bookmark in terminal": "Bookmark in terminal",
    "Bookmark terminals": "Bookmark terminals",
    "Stop bookmarking terminals": "Stop bookmarking terminals",
    "bookmark.tip": "Mark the scrollback where a turn ended or stopped for approval",
    "bookmark.label": "{agent} · {message} {time}",
    "bookmark.unsupported": "needs Hecaton API 1.21",
    "bookmark.blocked": "bookmarks blocked",
    "{count}s": "{count}s",
    "bookmark.comment.when": "{message} at {time}",
    "bookmark.comment.terminal": "Terminal: {name}",
    "bookmark.comment.model": "Model: {model}",
    "bookmark.comment.turn": "Turn time: {duration}"
  },
  "ko": {
    "permission.reason.service": "훅 서버와 에이전트 상태·북마크·알림을 하나의 백그라운드 서비스에서 처리합니다. 마지막 창을 닫은 뒤 최대 10분간 유지합니다.",
    "service.noService": "서비스 미등록: 창을 닫고 새로 여세요",
    "service.failed": "서비스 연결 실패 · 시작으로 재시도",
    "service.serverFailed": "{port} 포트 시작 실패 · 시작으로 재시도",
    "nav.dashboard": "대시보드",
    "nav.agents": "에이전트 상태",
    "nav.activity": "활동 기록",
    "Claude State": "Claude 상태",
    " Claude Dashboard ": " Claude 대시보드 ",
    "[a] Dashboard": "[a] 대시보드",
    "[h] Dashboard": "[h] 대시보드",
    "[r] Refresh": "[r] 새로고침",
    "[a] Agent State": "[a] 에이전트 상태",
    "[h] Heatmap": "[h] 활동 기록",
    "Back to dashboard": "대시보드로 돌아가기",
    "Loading...": "불러오는 중...",
    "No data": "데이터 없음",
    "No credentials found": "인증 정보를 찾을 수 없습니다",
    "Claude Status: Checking...": "Claude 상태: 확인 중...",
    "Claude Status: Unavailable": "Claude 상태: 확인 불가",
    "Claude Status: ": "Claude 상태: ",
    "Affected: ": "영향받는 구성 요소: ",
    "Claude Service Restored": "Claude 서비스 복구",
    "Claude services are operational again.": "Claude 서비스가 정상적으로 작동합니다.",
    "Plan: ": "요금제: ",
    "  Effort: ": "  추론 수준: ",
    "Rate Limits": "사용량 한도",
    "No rate limit data available": "사용량 한도 데이터가 없습니다",
    "Extra Usage": "추가 사용량",
    " spent": " 사용",
    "Remaining: ": "남은 양: ",
    "Extra usage enabled, no spend this period": "추가 사용량 활성화됨, 이번 기간 지출 없음",
    "Failed to fetch rate limits": "사용량 한도를 불러오지 못했습니다",
    "Check ~/.claude/.credentials.json": "~/.claude/.credentials.json을 확인하세요",
    "Session": "세션",
    "Uptime: ": "실행 시간: ",
    "Updated: ": "갱신: ",
    " (cached)": " (캐시)",
    "s ago": "초 전",
    " Activity Heatmap ": " 활동 기록 ",
    "(52 weeks)": "(52주)",
    "Loading heatmap data...": "활동 기록을 불러오는 중...",
    "No activity data available": "활동 데이터가 없습니다",
    "Less ": "적음 ",
    " More": " 많음",
    "Statistics": "통계",
    "Active days: ": "활동 일수: ",
    "Sessions: ": "세션 수: ",
    "Current streak: ": "연속 활동: ",
    "Longest: ": "최장 기록: ",
    " days": "일",
    "now": "지금",
    "5-hour limit": "5시간 한도",
    "7-day limit": "7일 한도",
    "Fable weekly limit": "Fable 주간 한도",
    "Stop": "중지",
    "Start": "시작",
    "  Hook Server  ": "  훅 서버  ",
    "  Pattern Match": "  패턴 감지",
    "stopped": "중지됨",
    "1.5s interval": "1.5초 간격",
    "off": "꺼짐",
    "Notify": "알림",
    "Previous preset": "이전 프리셋",
    "Cycle preset": "프리셋 전환",
    "Next preset": "다음 프리셋",
    "Reset to default preset": "기본 프리셋으로 초기화",
    "Reset": "초기화",
    "Suppress during compact": "압축 중 알림 억제",
    " Suppress during compact": " 압축 중 알림 억제",
    "Compaction fires Stop as a side effect": "컨텍스트 압축도 Stop 이벤트를 발생시킵니다",
    "Terminals": "터미널",
    "(none)": "(없음)",
    "Right-click for terminal actions": "우클릭으로 터미널 작업 열기",
    "  compacting": "  압축 중",
    "Log": "로그",
    "Clear log": "로그 지우기",
    "Clear": "지우기",
    "Install / update Claude Code hooks": "Claude Code 훅 설치 / 업데이트",
    "Stop hook server": "훅 서버 중지",
    "Start hook server": "훅 서버 시작",
    "Stop pattern matching": "패턴 감지 중지",
    "Start pattern matching": "패턴 감지 시작",
    "Reveal log file": "로그 파일 열기",
    "Quit": "닫기",
    "Install Claude Code Hooks": "Claude Code 훅 설치",
    "Install": "설치",
    "Cancel": "취소",
    "Screen-scraping fallback when hooks are unavailable": "훅을 사용할 수 없을 때 터미널 화면으로 상태를 감지합니다",
    "response complete": "응답 완료",
    "ended with an error": "오류로 종료됨",
    "needs permission": "권한 승인 필요",
    "session started": "세션 시작됨",
    "idle": "유휴",
    "strict": "엄격",
    "normal": "기본",
    "all": "전체",
    "custom": "사용자 지정",
    "running": "실행 중",
    "waiting": "응답 완료",
    "blocked": "승인 대기",
    "turn complete": "턴 완료",
    "turn ended with error": "오류로 턴 종료",
    "permission prompt (mid-turn)": "권한 승인 요청 (진행 중)",
    "permission.reason.startup": "Claude 작업이 끝났을 때, 승인을 기다리며 멈췄을 때, Claude 서비스 장애가 해소됐을 때 알려 드려 이 대시보드를 계속 보고 있지 않아도 되게 합니다. 알림에는 해당 터미널 이름을 표시하며 이러한 상태 변화에만 보냅니다.",
    "permission.reason.agent": "추적 중인 터미널의 Claude 세션이 작업을 마쳤거나, 오류로 끝났거나, 승인을 기다리고 있다는 사실을 알려 드립니다.",
    "permission.reason.recovery": "이 대시보드에 표시된 Claude 서비스 장애가 해소되는 즉시 알려 드려 작업을 이어갈 수 있게 합니다.",
    "permission.notify.blocked": "알림 차단됨",
    "permission.badge.blocked": "터미널 배지 차단됨",
    "session start / resume / clear": "세션 시작 / 재개 / 초기화",
    "idle prompt after 60s": "60초 후 유휴 알림",
    "Mon": "월",
    "Wed": "수",
    "Fri": "금",
    "Sun": "일",
    "Token expired or invalid (401). Re-login to Claude Code.": "토큰이 만료되었거나 유효하지 않습니다 (401). Claude Code에 다시 로그인하세요.",
    "{label}\nResets: {exact}\nRemaining: {remaining}": "{label}\n초기화: {exact}\n남은 시간: {remaining}",
    "{port} · {count} clients": "{port} · 연결 {count}개",
    "{action} hook server": "훅 서버 {action}",
    "Click to {action} the hook server": "클릭하여 훅 서버 {action}",
    "{action} pattern matching": "패턴 감지 {action}",
    "{action} {event} notification": "{event} 알림 {action}",
    "Enable": "켜기",
    "Disable": "끄기",
    "Allow notifications during compact": "압축 중 알림 허용",
    "Suppress notifications during compact": "압축 중 알림 억제",
    "Clear badge for {name}": "{name} 배지 지우기",
    "+{count} more": "+{count}개 더 있음",
    "Preset: {name}": "프리셋: {name}",
    "{who} — {message}": "{who} — {message}",
    "Add or update hooks in Claude Code settings.json\nto enable Claude State detection.\n\nTarget: {path}\nOut of date: {events}": "Claude 상태를 감지하도록 Claude Code의\nsettings.json에 훅을 추가하거나 업데이트합니다.\n\n대상: {path}\n업데이트 필요: {events}",
    "Network error: {error}": "네트워크 오류: {error}",
    "Failed to fetch: {error}": "불러오기 실패: {error}",
    "API error (HTTP {status})": "API 오류 (HTTP {status})",
    "API rate limited (429). Retrying in {minutes}min...": "API 요청 한도 초과 (429). {minutes}분 후 재시도...",
    "event.Stop": "응답 완료",
    "event.StopFailure": "오류 종료",
    "event.PermissionRequest": "권한 요청",
    "event.SessionStart": "세션 시작",
    "event.Idle": "유휴",
    "All Systems Operational": "모든 시스템 정상",
    "Partial System Outage": "일부 시스템 장애",
    "Major System Outage": "주요 시스템 장애",
    "Minor Service Outage": "경미한 서비스 장애",
    "Degraded System Service": "서비스 성능 저하",
    "DOWN": "장애",
    "Request failed": "요청 실패",
    "unknown": "알 수 없음",
    "{count}d": "{count}일",
    "{count}h": "{count}시간",
    "{count}m": "{count}분",
    "Jan": "1월",
    "Feb": "2월",
    "Mar": "3월",
    "Apr": "4월",
    "May": "5월",
    "Jun": "6월",
    "Jul": "7월",
    "Aug": "8월",
    "Sep": "9월",
    "Oct": "10월",
    "Nov": "11월",
    "Dec": "12월",
    "Bookmark in terminal": "터미널에 북마크",
    "Bookmark terminals": "터미널에 북마크 남기기",
    "Stop bookmarking terminals": "터미널 북마크 중지",
    "bookmark.tip": "작업이 끝나거나 승인을 기다리며 멈춘 지점을 스크롤백에 표시합니다",
    "bookmark.label": "{agent} · {message} {time}",
    "bookmark.unsupported": "Hecaton API 1.21 필요",
    "bookmark.blocked": "북마크 차단됨",
    "{count}s": "{count}초",
    "bookmark.comment.when": "{time}에 {message}",
    "bookmark.comment.terminal": "터미널: {name}",
    "bookmark.comment.model": "모델: {model}",
    "bookmark.comment.turn": "작업 시간: {duration}"
  }
};
// Catalogs are embedded by scripts/build.cjs; the host needs only main.js.
let uiLocale = 'en';
function setUiLocale(tag) {
  const normalized = String(tag || '').trim().replace(/_/g, '-').split('.')[0].toLowerCase();
  const next = Object.hasOwn(UI_CATALOGS, normalized) ? normalized : normalized.split('-')[0];
  uiLocale = Object.hasOwn(UI_CATALOGS, next) ? next : 'en';
}
function tr(key, args = {}) {
  const value = UI_CATALOGS[uiLocale][key] ?? UI_CATALOGS.en[key] ?? key;
  return value.replace(/\{(\w+)\}/g, (match, name) => Object.hasOwn(args, name) ? String(args[name]) : match);
}
// Host-facing text (permission prompts) is picked by the host, not by us: it
// takes a {en, ko, ...} map and applies its own plugin-language setting. Send
// every catalog we have and let it choose.
function translations(key, args = {}) {
  const map = {};
  for (const tag of Object.keys(UI_CATALOGS)) {
    const value = UI_CATALOGS[tag][key] ?? UI_CATALOGS.en[key];
    if (typeof value !== 'string' || !value.trim()) continue;
    map[tag] = value.replace(/\{(\w+)\}/g, (match, name) => Object.hasOwn(args, name) ? String(args[name]) : match);
  }
  return Object.keys(map).length ? map : tr(key, args);
}
function messageText(message) {
  return message && typeof message === 'object' ? tr(message.key, message.args) : tr(String(message || ''));
}
async function initUiLocale() {
  let tag = hecaton.initialState?.locale;
  if (!tag) {
    try { tag = (await hecaton.env.get({ name: 'HECA_LOCALE' })).value; } catch {}
  }
  if (!tag) {
    try { tag = (await hecaton.i18n.get_locale()).locale; } catch {}
  }
  setUiLocale(tag);
}
function cellWidth(ch) {
  const cp = ch.codePointAt(0);
  if (/\p{Mark}/u.test(ch) || cp === 0x200d || cp < 32 || (cp >= 0x7f && cp < 0xa0)) return 0;
  return (cp >= 0x1100 && cp <= 0x115f) || (cp >= 0x2e80 && cp <= 0xa4cf) ||
    (cp >= 0xac00 && cp <= 0xd7a3) || (cp >= 0xf900 && cp <= 0xfaff) ||
    (cp >= 0xfe10 && cp <= 0xfe6f) || (cp >= 0xff01 && cp <= 0xff60) ||
    (cp >= 0xffe0 && cp <= 0xffe6) || (cp >= 0x1f300 && cp <= 0x1faff) ||
    (cp >= 0x20000 && cp <= 0x3fffd) ? 2 : 1;
}
function displayWidth(text) {
  return [...String(text).replace(/\x1b\[[0-9;]*m/g, '')].reduce((sum, ch) => sum + cellWidth(ch), 0);
}
function clipCells(text, width) {
  let out = '', used = 0;
  for (const part of String(text).match(/\x1b\[[0-9;]*m|[^]/gu) || []) {
    const size = part.startsWith('\x1b[') ? 0 : cellWidth(part);
    if (used + size > Math.max(0, width)) break;
    out += part;
    used += size;
  }
  return out;
}
function padCells(text, width) {
  return text + ' '.repeat(Math.max(0, width - displayWidth(text)));
}
// Hecaton decides whether to start its RPC loop immediately after invoking the
// plugin. Awaiting an already-resolved helper here leaves no pending RPC or
// listener, so the runner exits before the first fs.read_file reply is handled.
// The normal host path must reach that first RPC without yielding.
if (hecaton.initialState?.locale) setUiLocale(hecaton.initialState.locale);
else await initUiLocale();

const notificationPermission = { state: 'unknown', granted: false };

function noteNotificationPermission(result) {
  if (!result || typeof result !== 'object') return;
  if (typeof result.state === 'string') notificationPermission.state = result.state;
  if (result.error_code === 'access_denied') notificationPermission.state = 'denied';
  notificationPermission.granted = notificationPermission.state === 'granted' ||
    (result.granted === true && notificationPermission.state !== 'denied');
}

function notificationsBlocked() {
  return notificationPermission.state === 'denied';
}

// False only for a decision already known to be "no". An unreachable
// permissions API is not a denial — let the send itself fail honestly.
async function ensureNotificationPermission(reasonKey) {
  try {
    noteNotificationPermission(await hecaton.permissions.query({ permission: 'notification' }));
    if (notificationPermission.state === 'denied') return false;
    if (notificationPermission.state !== 'prompt') return true;

    noteNotificationPermission(await hecaton.permissions.request({
      permission: 'notification',
      reason: translations(reasonKey),
    }));
    return notificationPermission.granted;
  } catch (e) {
    process.stderr.write('[claude-dashboard] Notification permission check failed: ' + (e.message || e) + '\n');
    return true;
  }
}

async function sendNotification(payload, reasonKey) {
  if (!await ensureNotificationPermission(reasonKey)) {
    process.stderr.write('[claude-dashboard] Notification suppressed: permission not granted\n');
    return { ok: false, error_code: 'access_denied' };
  }
  try {
    const result = await hecaton.notify.send(payload);
    if (result && result.ok === false) {
      noteNotificationPermission(result);
      process.stderr.write('[claude-dashboard] notify.send failed: ' + JSON.stringify(result) + '\n');
      return result;
    }
    return result || { ok: true };
  } catch (e) {
    process.stderr.write('[claude-dashboard] notify.send failed: ' + (e.message || e) + '\n');
    return { ok: false, error: e.message || String(e) };
  }
}


// Agent state controller, integrated from dev.hecaton.claude-hook v1.4.0.
function createClaudeState(host, options) {
let visible = false;
let disposed = false;
const sharedUI = !options.service;
let serviceChannel = null;
let connectedBefore = false;
let serviceError = null;
let remoteNotificationBlocked = false;
const backgroundEvents = new Set(['ws_connected', 'ws_message_received', 'ws_disconnected', 'http_request_received', 'terminal_changed']);
const uiEvents = new Set(['mouse_event', 'menu_requested', 'menu_activated']);
const hecaton = new Proxy(host, {
  get(target, key) {
    if (key === 'on') return (event, handler) => target.on(event, params => {
      if (sharedUI && backgroundEvents.has(event)) return;
      if (disposed || (uiEvents.has(event) && !visible)) return;
      return handler(params);
    });
    return target[key];
  },
});
/**
 * Claude State — Hecaton Plugin v1.4.0
 *
 * Detects AI agent state (Claude, Gemini, Codex, OpenCode, etc.)
 * and displays real-time status badges and notifications on terminal tabs.
 *
 * 2-tier detection:
 *   Tier 1 (Hook): Receives hook events via WebSocket/HTTP -> immediate state transition
 *   Tier 2 (Pattern): Terminal content pattern matching -> transition after 2 consecutive matches
 *
 * Hook protocol (WebSocket text or HTTP POST /hook):
 *   { "client": "claude", "terminal_id": 1, "event": "AfterAgent", ... }
 *
 * Notifications are per-event opt-in (see NOTIFY_EVENTS). Events that fire
 * mid-turn — PermissionRequest, SessionStart on resume/compact — are off by
 * default so a notification means the turn actually ended.
 *
 * Driven by mouse: every row is a toggle, buttons sit on the right, the wheel
 * scrolls the log, and right-click opens the full menu. Precise mouse events
 * are used when the host offers them, with SGR on stdin as the fallback.
 *
 * Keys (kept as a shortcut, not the primary path):
 *   s=toggle server  p=toggle pattern  n=cycle preset  c=clear log  q/ESC=quit
 */

// ============================================================
// Agent Patterns (inline — no ES module import)
// ============================================================
const AGENT_PATTERNS = {
  claude: {
    busy: ["ctrl+c to interrupt", "esc to interrupt"],
    busyRe: [/[✳✽✶✻✢·]\s*.+…/],
    prompt: ["$ "],
    promptRe: [/[❯>]\s*$/],
    detect: ["ctrl+c to interrupt", "Claude Code"],
    detectRe: [/[⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏]\s+\w+…/],
    spinner: "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏✳✽✶✻✢".split(""),
  },
  gemini: {
    busy: ["esc to cancel"], busyRe: [],
    prompt: ["gemini>", "Type your message"], promptRe: [],
    detect: ["gemini>", "esc to cancel"], detectRe: [],
    spinner: [],
  },
  codex: {
    busy: ["ctrl+c to interrupt"], busyRe: [],
    prompt: ["codex>"], promptRe: [],
    detect: ["codex>", "codex "], detectRe: [],
    spinner: [],
  },
  opencode: {
    busy: ["thinking...", "generating...", "esc interrupt"], busyRe: [],
    prompt: ["Ask anything", "press enter to send"], promptRe: [],
    detect: ["opencode", "Ask anything"], detectRe: [],
    spinner: [],
  },
  aider: {
    busy: [], busyRe: [/Tokens:\s+\d+/],
    prompt: [], promptRe: [/aider\s*>/i],
    detect: ["aider"], detectRe: [/aider\s*>/i],
    spinner: [],
  },
};

function matchLine(line, strings, regexps) {
  for (const s of strings) { if (line.includes(s)) return true; }
  for (const re of regexps) { if (re.test(line)) return true; }
  return false;
}

function detectAgent(lines) {
  for (const [agent, pat] of Object.entries(AGENT_PATTERNS)) {
    for (const line of lines) {
      if (matchLine(line, pat.detect, pat.detectRe || [])) return agent;
    }
  }
  return null;
}

function isBusy(lines, agent) {
  const pat = AGENT_PATTERNS[agent];
  if (!pat) return false;
  for (const line of lines) {
    if (matchLine(line, pat.busy, pat.busyRe || [])) return true;
  }
  if (pat.spinner && pat.spinner.length > 0) {
    const tail = lines.slice(-3);
    for (const line of tail) {
      for (const ch of pat.spinner) { if (line.includes(ch)) return true; }
    }
  }
  return false;
}

function isPrompt(lines, agent) {
  const pat = AGENT_PATTERNS[agent];
  if (!pat) return false;
  const tail = lines.slice(-3);
  for (const line of tail) {
    if (matchLine(line, pat.prompt, pat.promptRe || [])) return true;
  }
  return false;
}

// ============================================================
// State Machine (inline)
// ============================================================
class AgentStateMachine {
  constructor() {
    this.terminals = new Map();
    this.onTransition = null;
  }

  _get(terminalId) {
    if (!this.terminals.has(terminalId)) {
      this.terminals.set(terminalId, {
        state: null, agent: null, model: null, sessionId: null,
        lastTransition: 0, acknowledged: false,
        pendingState: null, pendingCount: 0,
      });
    }
    return this.terminals.get(terminalId);
  }

  setFromHook(terminalId, state, info = {}) {
    const ts = this._get(terminalId);
    const oldState = ts.state;
    ts.agent = info.agent || ts.agent;
    ts.model = info.model || ts.model;
    ts.sessionId = info.sessionId || ts.sessionId;
    ts.pendingState = null;
    ts.pendingCount = 0;

    if (state === "dead" || state === "end") {
      this.terminals.delete(terminalId);
      if (oldState && this.onTransition) {
        this.onTransition(terminalId, oldState, null, { agent: ts.agent, reason: "hook", ...info });
      }
      return;
    }
    if (oldState === state) return;
    ts.state = state;
    ts.lastTransition = Date.now();
    if (state === "waiting") ts.acknowledged = false;
    if (this.onTransition) {
      this.onTransition(terminalId, oldState, state, { agent: ts.agent, model: ts.model, reason: "hook", ...info });
    }
  }

  setFromPattern(terminalId, state, info = {}) {
    const ts = this._get(terminalId);
    ts.agent = info.agent || ts.agent;
    if (ts.state === state) { ts.pendingState = null; ts.pendingCount = 0; return; }
    if (ts.pendingState === state) {
      ts.pendingCount++;
      if (ts.pendingCount >= 2) {
        const oldState = ts.state;
        ts.state = state;
        ts.lastTransition = Date.now();
        ts.pendingState = null;
        ts.pendingCount = 0;
        if (state === "waiting") ts.acknowledged = false;
        if (this.onTransition) {
          this.onTransition(terminalId, oldState, state, { agent: ts.agent, reason: "pattern", ...info });
        }
      }
    } else {
      ts.pendingState = state;
      ts.pendingCount = 1;
    }
  }

  acknowledge(terminalId) {
    const ts = this.terminals.get(terminalId);
    if (ts && ts.state === "waiting" && !ts.acknowledged) ts.acknowledged = true;
  }

  getState(terminalId) { return this.terminals.get(terminalId) || null; }

  getAll() {
    return Array.from(this.terminals.entries()).map(([id, ts]) => ({ id, ...ts }));
  }

  remove(terminalId) { this.terminals.delete(terminalId); }
}

// ============================================================
// ANSI helpers
// ============================================================
const ESC = '\x1b';
const CSI = ESC + '[';
const ansi = {
  clear: CSI + '2J' + CSI + 'H',
  hideCursor: CSI + '?25l',
  showCursor: CSI + '?25h',
  reset: CSI + '0m',
  bold: CSI + '1m',
  dim: CSI + '2m',
  moveTo: (r, c) => `${CSI}${r};${c}H`,
  inverse: CSI + '7m',
  fg: {
    red: CSI + '31m', green: CSI + '32m', yellow: CSI + '33m',
    cyan: CSI + '36m', white: CSI + '37m', gray: CSI + '90m',
    orange: CSI + '38;5;215m', pink: CSI + '38;5;212m',
  },
  bg: {
    green: CSI + '42m', orange: CSI + '48;5;215m', gray: CSI + '100m',
    hover: CSI + '48;2;58;58;70m',
  },
};

// Only characters already proven to render at width 1 in this overlay are used
// for controls — a double-width glyph would shift every click zone on its row
// out of alignment with what the user sees.
const MARK_ON = '●';
const MARK_OFF = '○';

// ============================================================
// Notification config (inline — persisted to plugin data dir)
// ============================================================
const CONFIG_VERSION = 1;

// Order here drives the settings screen: [1]..[n] map to these rows.
const NOTIFY_EVENTS = [
  { key: 'Stop', label: 'Stop', desc: 'turn complete' },
  { key: 'StopFailure', label: 'StopFailure', desc: 'turn ended with error' },
  { key: 'PermissionRequest', label: 'PermissionRequest', desc: 'permission prompt (mid-turn)' },
  { key: 'SessionStart', label: 'SessionStart', desc: 'session start / resume / clear' },
  { key: 'Idle', label: 'Idle', desc: 'idle prompt after 60s' },
];

const PRESETS = {
  strict: { Stop: true, StopFailure: false, PermissionRequest: false, SessionStart: false, Idle: false },
  normal: { Stop: true, StopFailure: true, PermissionRequest: false, SessionStart: false, Idle: false },
  all: { Stop: true, StopFailure: true, PermissionRequest: true, SessionStart: true, Idle: true },
};
const PRESET_ORDER = ['strict', 'normal', 'all'];

const DEFAULT_CONFIG = {
  version: CONFIG_VERSION,
  preset: 'normal',
  notify: { ...PRESETS.normal },
  suppressDuringCompact: true,
  // Mark the terminal's scrollback where a turn ended or stopped for approval.
  bookmarks: true,
};

let config = JSON.parse(JSON.stringify(DEFAULT_CONFIG));
let configFile = null;

function presetNameFor(notify) {
  for (const name of PRESET_ORDER) {
    const p = PRESETS[name];
    if (NOTIFY_EVENTS.every(e => !!p[e.key] === !!notify[e.key])) return name;
  }
  return 'custom';
}

async function envValue(name) {
  try {
    const r = await hecaton.env.get({ name });
    return (r && r.value) ? r.value : null;
  } catch { return null; }
}

// Notification prefs are global, not per-project — prefer the shared data dir.
async function resolveConfigDir() {
  const shared = await envValue('HECA_PLUGIN_DATA_DIR');
  if (shared) return shared.replace(/\\/g, '/');
  try {
    const home = await hecaton.env.get_home();
    const path = home && (home.path || home.value);
    if (path) return `${path}/.hecaton/data/dev.hecaton.claude-dashboard`;
  } catch { /* ignore */ }
  return null;
}

async function initLogFile() {
  try {
    const home = await hecaton.env.get_home();
    const base = home && (home.path || home.value);
    if (!base) return;
    logFilePath = `${base}/.claude/hecaton-agent-state.log`;
    addLog(`=== plugin start (port ${PORT}) — log: ${logFilePath}`);
  } catch { /* ignore */ }
}

async function loadConfig() {
  const dir = await resolveConfigDir();
  if (!dir) { addLog('Config dir unavailable — using defaults'); return; }
  configFile = `${dir}/agent-state.json`;
  try {
    let result;
    try { result = await hecaton.fs.read_file({ path: configFile }); } catch { /* try legacy preferences */ }
    if (!result?.content) {
      const home = await hecaton.env.get_home();
      const base = home.path || home.value;
      const legacyDirs = [
        dir.replace(/claude-dashboard/g, 'claude-hook'),
        `${base}/.hecaton/data/dev_hecaton_claude-hook`,
        `${base}/.hecaton/data/dev.hecaton.claude-hook`,
      ];
      for (const legacy of new Set(legacyDirs)) {
        try { result = await hecaton.fs.read_file({ path: `${legacy}/config.json` }); } catch { continue; }
        if (result?.content) break;
      }
    }
    if (!result || !result.content) return;
    const parsed = JSON.parse(result.content);
    if (!parsed || parsed.version !== CONFIG_VERSION) return;
    const notify = { ...DEFAULT_CONFIG.notify };
    if (parsed.notify && typeof parsed.notify === 'object') {
      for (const e of NOTIFY_EVENTS) {
        if (typeof parsed.notify[e.key] === 'boolean') notify[e.key] = parsed.notify[e.key];
      }
    }
    config = {
      version: CONFIG_VERSION,
      notify,
      preset: presetNameFor(notify),
      suppressDuringCompact: typeof parsed.suppressDuringCompact === 'boolean'
        ? parsed.suppressDuringCompact
        : DEFAULT_CONFIG.suppressDuringCompact,
      bookmarks: typeof parsed.bookmarks === 'boolean' ? parsed.bookmarks : DEFAULT_CONFIG.bookmarks,
    };
    addLog(`Config loaded (preset: ${config.preset})`);
  } catch {
    // Missing or corrupt file — defaults already in place
  }
}

async function saveConfig() {
  if (!configFile) return;
  try {
    const dir = configFile.replace(/\/[^/]*$/, '');
    await hecaton.fs.mkdir({ path: dir }).catch(() => null);
    await hecaton.fs.write_file({ path: configFile, content: JSON.stringify(config, null, 2) });
  } catch (e) {
    addLog(`Config save failed: ${e.message || e}`);
  }
}

function applyPreset(name) {
  const p = PRESETS[name];
  if (!p) return;
  config.notify = { ...p };
  config.preset = name;
}

function toggleNotifyEvent(index) {
  const entry = NOTIFY_EVENTS[index];
  if (!entry) return;
  config.notify[entry.key] = !config.notify[entry.key];
  config.preset = presetNameFor(config.notify);
}

function cyclePreset() {
  const idx = PRESET_ORDER.indexOf(config.preset);
  applyPreset(PRESET_ORDER[(idx + 1) % PRESET_ORDER.length]);
}

// ============================================================
// State
// ============================================================
let termCols = parseInt(hecaton.initialState?.cols || '80', 10);
let termRows = parseInt(hecaton.initialState?.rows || '24', 10);

// 9200 and 9217 were both abandoned after leaked listeners from earlier builds
// took them over — see reclaimPreviousServer(), which stops that from recurring.
// A port only needs changing again if a listener leaks from a build without it.
const PORT = 9218;
let serverId = null;
let serverRunning = false;
let serverError = null;
let patternEnabled = false;
let subscriptionId = null;
// Set once terminal_status is refused: the badge is optional decoration, and
// re-asking on every transition would turn one refusal into a prompt storm.
let badgesBlocked = false;
const connections = new Map();
const log = [];
const MAX_LOG = 200;

// Terminals currently inside a PreCompact..PostCompact window, keyed by id.
// Claude Code fires Stop for compaction too, so that window has to be ignored.
const compacting = new Map();
const COMPACT_TIMEOUT_MS = 180000;

// ── Terminal naming ────────────────────────────────────────
// "T2496" is the host's internal id and means nothing to a human. Ask the host
// what each terminal actually is and show that instead. The response shape is
// not documented, so every plausible field is probed and the raw payload is
// logged once so the mapping can be corrected against reality.
const terminalInfo = new Map();
let terminalListLogged = false;
let terminalListMissing = false;

// Titles that are just the shell tell us nothing the id doesn't.
const GENERIC_TITLES = new Set([
  'cmd', 'cmd.exe', 'bash', 'sh', 'zsh', 'fish', 'powershell', 'powershell.exe',
  'pwsh', 'pwsh.exe', 'wsl', 'wsl.exe', 'terminal', 'console', 'shell', 'node',
]);

function baseName(p) {
  const s = String(p || '').replace(/[\\/]+$/, '');
  const cut = Math.max(s.lastIndexOf('/'), s.lastIndexOf('\\'));
  return cut === -1 ? s : s.slice(cut + 1);
}

// The host reports { alias, cwd, shell, id, ... }. An alias is user-chosen and
// always wins; otherwise the working directory names the terminal far better
// than its id. `title` and friends are kept as a cushion for other host builds.
function pickTerminalLabel(t) {
  const alias = String(t.alias || '').trim();
  if (alias) return alias;
  const title = t.title || t.name || t.label || t.tab_title || t.tabTitle || '';
  const cwd = t.cwd || t.path || t.directory || t.working_directory || t.workingDirectory || '';
  const folder = cwd ? baseName(cwd) : '';
  const named = title && !GENERIC_TITLES.has(String(title).trim().toLowerCase());
  return String(named ? title : (folder || title) || '').trim();
}

async function refreshTerminalInfo() {
  if (terminalListMissing) return;
  try {
    const r = await hecaton.terminal.list();
    if (r && r.ok === false) {
      terminalListMissing = true;
      addLog(`terminal.list refused: ${r.error_code || r.error || 'unknown'} — notifications will use terminal ids`);
      return;
    }
    if (!terminalListLogged) {
      terminalListLogged = true;
      addLog(`terminal.list → ${JSON.stringify(r).slice(0, 240)}`);
    }
    const arr = Array.isArray(r) ? r
      : (r && (r.terminals || r.list || r.items || r.result)) || [];
    if (!Array.isArray(arr)) return;
    terminalInfo.clear();
    for (const t of arr) {
      if (!t || typeof t !== 'object') continue;
      const id = t.id ?? t.terminal_id ?? t.terminalId;
      if (id === undefined || id === null) continue;
      const label = pickTerminalLabel(t);
      if (label) terminalInfo.set(Number(id), label);
    }
  } catch (e) {
    terminalListMissing = true;
    addLog(`terminal.list unavailable: ${e && e.message ? e.message : e}`);
  }
}

// Display name for a terminal — its real name when the host knows one.
function terminalLabel(id, max = 20) {
  const name = terminalInfo.get(id);
  if (!name) return `T${id}`;
  return displayWidth(name) > max ? clipCells(name, max - 1) + '…' : name;
}

function isCompacting(terminalId) {
  const since = compacting.get(terminalId);
  if (!since) return false;
  if (Date.now() - since > COMPACT_TIMEOUT_MS) { compacting.delete(terminalId); return false; }
  return true;
}

// ============================================================
// State Machine
// ============================================================
const sm = new AgentStateMachine();

function snapshot() {
  return { config, serverRunning, serverError, patternEnabled, badgesBlocked, bookmarksUnavailable,
    terminals: sm.getAll(), terminalInfo: [...terminalInfo], connections: [...connections],
    compacting: [...compacting], log: log.slice(), logFilePath, configFile,
    notificationBlocked: notificationsBlocked() };
}

function applySnapshot(data) {
  if (disposed || !data) return;
  serviceError = null;
  config = data.config;
  serverRunning = data.serverRunning;
  serverError = data.serverError;
  patternEnabled = data.patternEnabled;
  badgesBlocked = data.badgesBlocked;
  bookmarksUnavailable = data.bookmarksUnavailable;
  sm.terminals = new Map(data.terminals.map(({ id, ...value }) => [id, value]));
  for (const [map, entries] of [[terminalInfo, data.terminalInfo], [connections, data.connections], [compacting, data.compacting]]) {
    map.clear();
    for (const [key, value] of entries) map.set(key, value);
  }
  log.splice(0, log.length, ...data.log);
  logFilePath = data.logFilePath;
  configFile = data.configFile;
  remoteNotificationBlocked = data.notificationBlocked;
  rerender();
}

async function serviceRequest(method = 'status', params = {}) {
  if (disposed) return;
  try {
    if (!serviceChannel) {
      if (typeof host.serviceChannel !== 'function') throw new Error('service_unsupported');
      serviceChannel = host.serviceChannel({
        protocol: 1, reason: translations('permission.reason.service'),
        onNotify: (method, data) => { if (method === 'state') applySnapshot(data); },
        onConnected: () => { if (connectedBefore) serviceRequest(); },
        onDisconnected: () => { serviceError = 'service_disconnected'; serverRunning = false; rerender(); },
      });
    }
    await serviceChannel.connect();
    if (disposed) { await serviceChannel.close(); return; }
    connectedBefore = true;
    applySnapshot(await serviceChannel.request(method, params, 120000));
  } catch (e) {
    if (disposed) return;
    serviceError = [e.code, e.message].filter(Boolean).join(': ');
    serverRunning = false;
    addLog('Background service: ' + serviceError);
  }
}

const STATE_COLORS = {
  running: '#50FA7B',   // green
  waiting: '#FFB86C',   // orange
  blocked: '#FF79C6',   // pink — waiting on the user, turn not over
  idle: '#6272A4',      // gray
};
const STATE_ICONS = {
  running: '●',
  waiting: '◐',
  blocked: '◍',
  idle: '○',
};
const STATE_FG = {
  running: ansi.fg.green,
  waiting: ansi.fg.orange,
  blocked: ansi.fg.pink,
  idle: ansi.fg.gray,
};
// Most attention-worthy first — the minimized bar only has room for a couple.
const STATE_ORDER = ['blocked', 'running', 'waiting', 'idle'];

// Hook event -> notification config key. Events absent here never notify,
// which is what keeps mid-turn traffic (PostToolUse, PreCompact, ...) quiet.
const NOTIFY_KEY_BY_EVENT = {
  'Stop': 'Stop',
  'AfterAgent': 'Stop',
  'response': 'Stop',
  'StopFailure': 'StopFailure',
  'PermissionRequest': 'PermissionRequest',
  'SessionStart': 'SessionStart',
  'Notification': 'Idle',
};

const NOTIFY_BODY = {
  Stop: (who) => tr('{who} — {message}', { who, message: tr('response complete') }),
  StopFailure: (who) => tr('{who} — {message}', { who, message: tr('ended with an error') }),
  PermissionRequest: (who) => tr('{who} — {message}', { who, message: tr('needs permission') }),
  SessionStart: (who) => tr('{who} — {message}', { who, message: tr('session started') }),
  Idle: (who) => tr('{who} — {message}', { who, message: tr('idle') }),
};

// What to call this terminal in a notification: its real name when the host
// knows one, otherwise the agent plus the raw id.
function describeTerminal(id, agent) {
  return terminalInfo.get(id) || `${agent || 'claude'} T${id}`;
}

// Same event on the same terminal within this window is treated as a duplicate.
const NOTIFY_DEDUPE_MS = 5000;
const lastNotify = new Map();

function shouldNotify(terminalId, key) {
  if (!key || !config.notify[key]) return false;
  const mapKey = `${terminalId}:${key}`;
  const prev = lastNotify.get(mapKey) || 0;
  const now = Date.now();
  if (now - prev < NOTIFY_DEDUPE_MS) return false;
  lastNotify.set(mapKey, now);
  return true;
}

// terminal_status is a separate grant from terminal_list. Refusing it should
// cost the badge and nothing else — state tracking and notifications carry on.
async function setTerminalBadge(terminalId, badge) {
  if (badgesBlocked) return;
  try {
    const r = await hecaton.terminal.set_status({ terminal_id: terminalId, ...badge });
    if (r && r.ok === false) {
      badgesBlocked = r.error_code === 'access_denied';
      addLog(`terminal.set_status refused: ${r.error_code || r.error || 'unknown'}`);
      if (badgesBlocked) rerender();
    }
  } catch (e) {
    addLog(`terminal.set_status failed: ${e && e.message ? e.message : e}`);
  }
}

const CLEAR_BADGE = { label: '', icon: '', color: '', detail: '' };

// ── Scrollback bookmarks ───────────────────────────────────
// A notification says *that* a turn ended; a bookmark says *where*. The host
// (API 1.21) drops it on the terminal's cursor row at the moment of the call,
// which for a hook is where Claude's output stopped, and shows it on the scroll
// map and scrollbar like a bookmark the user made by hand.
const BOOKMARK_MESSAGE = {
  Stop: 'response complete',
  StopFailure: 'ended with an error',
  PermissionRequest: 'needs permission',
};
const lastBookmark = new Map();
// null = not decided yet; a string is why bookmarks are off for this run.
let bookmarksUnavailable = null;
// When each terminal's current turn started running, for the bookmark comment.
const turnStartedAt = new Map();

// Turns are often shorter than a minute, so unlike formatDuration this keeps seconds.
function formatTurnDuration(ms) {
  const totalSec = Math.max(0, Math.round(ms / 1000));
  const hours = Math.floor(totalSec / 3600);
  const minutes = Math.floor((totalSec % 3600) / 60);
  const seconds = totalSec % 60;
  if (hours > 0) return tr('{count}h', { count: hours }) + ' ' + tr('{count}m', { count: minutes });
  if (minutes > 0) return tr('{count}m', { count: minutes }) + ' ' + tr('{count}s', { count: seconds });
  return tr('{count}s', { count: seconds });
}

// The label stays one short line on the chip; the comment carries the details
// you see when hovering it: exact time, terminal, model and how long the turn ran.
function bookmarkComment(terminalId, key, info) {
  const pad = (n) => String(n).padStart(2, '0');
  const d = new Date();
  const lines = [tr('bookmark.comment.when', {
    message: tr(BOOKMARK_MESSAGE[key]),
    time: `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ` +
      `${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`,
  })];
  lines.push(tr('bookmark.comment.terminal', { name: describeTerminal(terminalId, info.agent) }));
  if (info.model) lines.push(tr('bookmark.comment.model', { model: info.model }));
  const started = turnStartedAt.get(terminalId);
  if (started) lines.push(tr('bookmark.comment.turn', { duration: formatTurnDuration(Date.now() - started) }));
  return lines.join('\n');
}

function shouldBookmark(terminalId, key) {
  if (!config.bookmarks || bookmarksUnavailable || !BOOKMARK_MESSAGE[key]) return false;
  // 0 is "my own terminal" to the host — pattern matching has no real target.
  if (!terminalId) return false;
  const mapKey = `${terminalId}:${key}`;
  const now = Date.now();
  if (now - (lastBookmark.get(mapKey) || 0) < NOTIFY_DEDUPE_MS) return false;
  lastBookmark.set(mapKey, now);
  return true;
}

function bookmarkLabel(agent, key) {
  const name = !agent || agent === 'claude' ? 'Claude' : agent;
  const time = new Date().toTimeString().slice(0, 5);
  return tr('bookmark.label', { agent: name, message: tr(BOOKMARK_MESSAGE[key]), time });
}

async function addTerminalBookmark(terminalId, agent, key, info) {
  // Older hosts do not have the method at all; the runner builds the API from
  // the host's own method table, so it is simply missing.
  if (typeof hecaton.terminal?.add_bookmark !== 'function') {
    bookmarksUnavailable = 'unsupported';
    addLog('terminal.add_bookmark unavailable — host older than API 1.21, bookmarks off');
    return;
  }
  try {
    const r = await hecaton.terminal.add_bookmark({
      terminal_id: terminalId,
      label: bookmarkLabel(agent, key),
      comment: bookmarkComment(terminalId, key, { ...info, agent }),
    });
    if (r && r.ok === false) {
      // Same grant as the badge; a refusal is stored by the host, so stop asking.
      if (r.error_code === 'access_denied') bookmarksUnavailable = 'access_denied';
      addLog(`terminal.add_bookmark refused: ${r.error_code || r.error || 'unknown'}`);
      if (bookmarksUnavailable) rerender();
    }
  } catch (e) {
    addLog(`terminal.add_bookmark failed: ${e && e.message ? e.message : e}`);
  }
}

sm.onTransition = async (terminalId, from, to, info) => {
  const agent = info.agent || 'unknown';

  if (to === null) {
    addLog(`[${agent}] T${terminalId} session ended`);
    lastNotify.delete(`${terminalId}:Stop`);
    compacting.delete(terminalId);
    turnStartedAt.delete(terminalId);
    await setTerminalBadge(terminalId, CLEAR_BADGE);
    return;
  }

  const icon = STATE_ICONS[to] || '?';
  const color = STATE_COLORS[to] || '#FFFFFF';
  const label = `${icon} ${agent}`;
  const detail = info.model ? `${info.model} (${tr(to)})` : tr(to);

  addLog(`[${agent}] T${terminalId} ${from || 'null'} → ${to} (${info.reason || '?'})`);

  await setTerminalBadge(terminalId, { label, icon: 'radio-tower', color, detail });

  // Pattern matching has no hook event — its running->waiting means "turn done".
  const key = info.reason === 'pattern'
    ? (from === 'running' && to === 'waiting' ? 'Stop' : null)
    : NOTIFY_KEY_BY_EVENT[info.event];

  // A turn starts when the agent starts running; an approval stop (blocked)
  // and its resume back to running stay inside the same turn.
  if (to === 'running' && from !== 'running' && from !== 'blocked') turnStartedAt.set(terminalId, Date.now());

  // Bookmarks follow their own toggle: muting a notification should not also
  // lose the place in the scrollback.
  if (shouldBookmark(terminalId, key)) await addTerminalBookmark(terminalId, agent, key, info);
  if (to !== 'running' && to !== 'blocked') turnStartedAt.delete(terminalId);

  if (!shouldNotify(terminalId, key)) return;

  const body = (NOTIFY_BODY[key] || NOTIFY_BODY.Stop)(describeTerminal(terminalId, agent));
  await sendNotification({ terminal_id: terminalId, title: tr('Claude State'), body }, 'permission.reason.agent');
  rerender();
};

// ============================================================
// Hook event → state mapping
// ============================================================
const EVENT_STATE_MAP = {
  'SessionStart': 'waiting',
  'BeforeAgent': 'running',
  'UserPromptSubmit': 'running',
  'PreToolUse': 'running',
  'PermissionDenied': 'running',
  'PermissionRequest': 'blocked',
  'AfterAgent': 'waiting',
  'Stop': 'waiting',
  'StopFailure': 'waiting',
  'Notification': 'idle',
  'SessionEnd': 'dead',
  'running': 'running',
  'waiting': 'waiting',
  'idle': 'idle',
  'response': 'waiting',
};

// Events that adjust bookkeeping instead of driving a state transition.
const COMPACT_ENTER = 'PreCompact';
const COMPACT_EXIT = 'PostCompact';

function processHookEvent(data) {
  if (!data || typeof data !== 'object' || Array.isArray(data)) return;
  const client = data.client || 'unknown';
  const rawId = parseInt(data.terminal_id, 10);
  const terminalId = Number.isFinite(rawId) ? rawId : 0;
  const event = data.event || data.hook_event_name || 'unknown';
  const model = data.model || '';
  const sessionId = data.session_id || '';

  // Compaction fires Stop as a side effect. Bracket it and drop what lands inside.
  if (event === COMPACT_ENTER) {
    compacting.set(terminalId, Date.now());
    addLog(`[${client}] T${terminalId} compact started`);
    return;
  }
  if (event === COMPACT_EXIT) {
    compacting.delete(terminalId);
    addLog(`[${client}] T${terminalId} compact finished`);
    return;
  }

  // Sole job: take a terminal out of `blocked` once the user answers the prompt.
  // Deliberately ignored otherwise, so a PostToolUse racing a Stop can't undo it.
  if (event === 'PostToolUse') {
    const ts = sm.getState(terminalId);
    if (ts && ts.state === 'blocked') {
      sm.setFromHook(terminalId, 'running', { agent: client, model, sessionId, event, reason: event });
    }
    return;
  }

  // SessionStart also fires on resume/clear/compact. Mid-turn it means the
  // session was reloaded, not that the turn ended — leaving `running` alone
  // keeps the later Stop a real transition instead of a no-op.
  if (event === 'SessionStart') {
    const ts = sm.getState(terminalId);
    if (ts && (ts.state === 'running' || ts.state === 'blocked')) {
      addLog(`[${client}] T${terminalId} SessionStart ignored (mid-turn)`);
      return;
    }
  }

  // A terminal we have no name for is worth one lookup — names are stable, so
  // this fires once per terminal rather than once per event.
  if (!terminalInfo.has(terminalId)) refreshTerminalInfo();

  const state = EVENT_STATE_MAP[event];
  if (!state) {
    addLog(`[${client}] T${terminalId} unknown event: ${event}`);
    return;
  }

  if (config.suppressDuringCompact && isCompacting(terminalId) && (event === 'Stop' || event === 'SessionStart')) {
    addLog(`[${client}] T${terminalId} ${event} ignored (compacting)`);
    return;
  }

  sm.setFromHook(terminalId, state, { agent: client, model, sessionId, event, reason: event });
}

// ============================================================
// Pattern matching (Tier 2)
// ============================================================
let lastCellVersion = 0;

async function onTerminalChanged(params) {
  if (!patternEnabled) return;
  try {
    const cells = await hecaton.terminal.get_cells({ since_version: 0 });
    if (cells && cells.ok === false) {
      addLog(`terminal.get_cells refused: ${cells.error_code || cells.error || 'unknown'}`);
      await stopPatternMatching();
      return;
    }
    if (!cells || !cells.rows_data) return;
    if (cells.version === lastCellVersion) return;
    lastCellVersion = cells.version;

    const rows = cells.rows;
    const cols = cells.cols;
    const rowsData = cells.rows_data;

    const lines = [];
    const startRow = Math.max(0, rows - 10);
    for (let r = startRow; r < rows; r++) {
      const rowEntry = rowsData[r];
      if (!rowEntry || !rowEntry.data) { lines.push(''); continue; }
      const raw = atob(rowEntry.data);
      let lineText = '';
      for (let c = 0; c < cols; c++) {
        const offset = c * 12;
        if (offset + 4 > raw.length) break;
        const cp = raw.charCodeAt(offset)
          | (raw.charCodeAt(offset + 1) << 8)
          | (raw.charCodeAt(offset + 2) << 16)
          | (raw.charCodeAt(offset + 3) << 24);
        lineText += cp > 0 ? String.fromCodePoint(cp) : ' ';
      }
      lines.push(lineText.trimEnd());
    }

    while (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();
    if (lines.length === 0) return;

    const agent = detectAgent(lines);
    if (!agent) return;

    const terminalId = 0;
    if (isBusy(lines, agent)) {
      sm.setFromPattern(terminalId, 'running', { agent });
    } else if (isPrompt(lines, agent)) {
      sm.setFromPattern(terminalId, 'waiting', { agent });
    }
  } catch (e) {
    addLog(`Pattern error: ${e.message || e}`);
  }
}

// ============================================================
// WebSocket/HTTP server
// ============================================================
// The shared service owns its listener; server ids cannot be reclaimed by another instance.
async function startServer() {
  if (serverRunning) return;
  serverError = null;
  addLog(`Starting Claude State server on port ${PORT}...`);


  let result;
  try { result = await hecaton.web.serve({ port: PORT, host: '127.0.0.1' }); }
  catch (e) { result = { ok: false, error: e.message || String(e) }; }
  if (disposed) {
    if (result?.ok) await hecaton.web.stop({ server_id: result.server_id });
    return;
  }
  if (!result || !result.ok) {
    serverError = result?.error_code || result?.error || 'unknown';
    addLog(`Server failed: ${serverError}`);
    return;
  }

  serverId = result.server_id;
  serverRunning = true;
  addLog(`Server running on ws://127.0.0.1:${result.port} (id ${serverId})`);

  await hecaton.web.set_http({
    server_id: serverId,
    content_type: 'application/json',
    body: JSON.stringify({ status: 'ok', message: 'Claude State Hook Server' }),
  });

  rerender();
}

async function stopServer() {
  if (!serverRunning) return;
  if (serverId !== null) {
    await hecaton.web.stop({ server_id: serverId });
    serverId = null;
  }
  connections.clear();
  serverRunning = false;
  addLog('Server stopped');
  rerender();
}

// ============================================================
// Pattern subscription
// ============================================================
async function startPatternMatching() {
  if (patternEnabled) return;
  patternEnabled = true;
  addLog('Pattern matching enabled (1.5s interval)');

  const result = await hecaton.terminal.subscribe({ interval_ms: 1500 });
  if (disposed) {
    if (result?.subscription_id != null) {
      await hecaton.terminal.unsubscribe({ subscription_id: result.subscription_id });
    }
    return;
  }
  if (result && result.subscription_id) {
    subscriptionId = result.subscription_id;
    addLog(`Subscribed: ${subscriptionId}`);
  } else {
    // cross_terminal refused, or the host has no subscription API: the screen
    // reader can never fire, so turn the toggle back off instead of lying.
    patternEnabled = false;
    addLog(`terminal.subscribe failed: ${result && (result.error_code || result.error) || 'no subscription id'}`);
  }
  rerender();
}

async function stopPatternMatching() {
  if (!patternEnabled) return;
  patternEnabled = false;
  if (subscriptionId) {
    await hecaton.terminal.unsubscribe({ subscription_id: subscriptionId });
    subscriptionId = null;
  }
  addLog('Pattern matching disabled');
  rerender();
}

// ============================================================
// Render
// ============================================================
// The on-screen log dies with the overlay, which makes "did the hook even
// arrive?" impossible to answer after the fact. Mirror it to a file under
// ~/.claude (already covered by this plugin's fs_write grant). Coalesced, and
// failures are swallowed — diagnostics must never break the plugin.
let logFilePath = null;
let logFlushTimer = null;

function scheduleLogFlush() {
  if (sharedUI) return;
  if (!logFilePath || logFlushTimer) return;
  logFlushTimer = setTimeout(async () => {
    logFlushTimer = null;
    try {
      await hecaton.fs.write_file({
        path: logFilePath,
        content: log.slice().reverse().join('\n') + '\n',
      });
    } catch { /* diagnostics only */ }
  }, 300);
}

function addLog(msg) {
  const time = new Date().toLocaleTimeString('en-US', { hour12: false });
  log.unshift(`${time} ${msg}`);
  if (log.length > MAX_LOG) log.pop();
  scheduleLogFlush();
  rerender();
}

// ── Click zones ────────────────────────────────────────────
// Rebuilt on every render. Hover is stored as a coordinate rather than a zone
// index so a zone can decide its own highlight as it is being drawn — the zone
// list does not exist yet at that point.
let clickZones = [];
let hoverRow = -1;
let hoverCol = -1;
let logScroll = 0;
let panelScroll = 0;
let appliedCursor = null;
let appliedTooltip = null;
let minimized = hecaton.initialState?.minimized ?? false;

// `label` is what the context menu calls this control; `tip` is the hover
// tooltip. Both optional — plain regions (log lines) register neither.
function zone(row, colStart, colEnd, action, opts = {}) {
  row += 2 - panelScroll;
  if (row < 3 || row > termRows) return false;
  clickZones.push({ row, colStart, colEnd, action, ...opts });
  return hoverRow === row && hoverCol >= colStart && hoverCol <= colEnd;
}

function zoneAt(row, col) {
  for (const z of clickZones) {
    if (z.row === row && col >= z.colStart && col <= z.colEnd) return z;
  }
  return null;
}

function chip(text, on, hot) {
  const body = on ? ansi.fg.green : ansi.fg.gray;
  return (hot ? ansi.bg.hover : '') + body + text + ansi.reset;
}

function button(label, hot, tone) {
  const text = `[ ${label} ]`;
  const color = tone || ansi.fg.cyan;
  return (hot ? ansi.bg.hover + ansi.bold : ansi.dim) + color + text + ansi.reset;
}

function rerender() {
  if (options.service) {
    if (!disposed) options.onChange?.(snapshot());
    return;
  }
  if (disposed || !visible) return;
  if (minimized) return;

  clickZones = [];
  const W = Math.max(40, termCols);
  const H = Math.max(28, termRows - 2);
  panelScroll = Math.min(panelScroll, Math.max(0, H - (termRows - 2)));
  let out = ansi.hideCursor + ansi.clear;

  // Title
  out += ansi.moveTo(1, 2) + ansi.bold + ansi.fg.orange + tr('Claude State') + ansi.reset;
  // ── Hook server ──
  let row = 3;
  {
    const btnLabel = serverRunning ? tr('Stop') : tr('Start');
    const btnCol = Math.max(20, W - 11);
    const markHot = zone(row, 2, 17, 'toggle-server',
      { label: tr('{action} hook server', { action: btnLabel }), tip: tr('Click to {action} the hook server', { action: btnLabel.toLowerCase() }) });
    out += ansi.moveTo(row, 2) + chip(serverRunning ? MARK_ON : MARK_OFF, serverRunning, markHot);
    out += (markHot ? ansi.bg.hover : '') + tr('  Hook Server  ') + ansi.reset;

    out += ansi.moveTo(row, 19) + ansi.dim;
    out += serviceError ? tr(serviceError.includes('no_service') ? 'service.noService' : 'service.failed')
      : serverError ? tr('service.serverFailed', { port: PORT })
      : serverRunning ? tr('{port} · {count} clients', { port: PORT, count: connections.size }) : tr('stopped');
    out += ansi.reset;

    const btnHot = zone(row, btnCol, btnCol + displayWidth(btnLabel) + 3, 'toggle-server',
      { label: tr('{action} hook server', { action: btnLabel }) });
    out += ansi.moveTo(row, btnCol) + button(btnLabel, btnHot, serverRunning ? ansi.fg.red : ansi.fg.green);
  }

  // ── Pattern matching ──
  row = 4;
  {
    const btnLabel = patternEnabled ? tr('Stop') : tr('Start');
    const btnCol = Math.max(20, W - 11);
    const markHot = zone(row, 2, 17, 'toggle-pattern',
      { label: tr('{action} pattern matching', { action: btnLabel }), tip: tr('Screen-scraping fallback when hooks are unavailable') });
    out += ansi.moveTo(row, 2) + chip(patternEnabled ? MARK_ON : MARK_OFF, patternEnabled, markHot);
    out += (markHot ? ansi.bg.hover : '') + tr('  Pattern Match') + ansi.reset;

    out += ansi.moveTo(row, 19) + ansi.dim;
    out += patternEnabled ? tr('1.5s interval') : tr('off');
    out += ansi.reset;

    const btnHot = zone(row, btnCol, btnCol + displayWidth(btnLabel) + 3, 'toggle-pattern',
      { label: tr('{action} pattern matching', { action: btnLabel }) });
    out += ansi.moveTo(row, btnCol) + button(btnLabel, btnHot, patternEnabled ? ansi.fg.red : ansi.fg.green);
  }

  // ── Notify ──
  row = 6;
  {
    out += ansi.moveTo(row, 2) + ansi.bold + tr('Notify') + ansi.reset;

    const prevHot = zone(row, 10, 10, 'preset-prev', { label: tr('Previous preset') });
    out += ansi.moveTo(row, 10) + (prevHot ? ansi.bg.hover + ansi.bold : ansi.dim) + '<' + ansi.reset;

    const name = padCells(clipCells(tr(config.preset), 6), 6);
    const nameHot = zone(row, 12, 12 + displayWidth(name) - 1, 'preset-next', { label: tr('Cycle preset') });
    out += ansi.moveTo(row, 12) + (nameHot ? ansi.bg.hover : '') + ansi.fg.orange + name + ansi.reset;

    const nextHot = zone(row, 19, 19, 'preset-next', { label: tr('Next preset') });
    out += ansi.moveTo(row, 19) + (nextHot ? ansi.bg.hover + ansi.bold : ansi.dim) + '>' + ansi.reset;

    // A screen of notification toggles is a lie once the host has refused the
    // permission — say so where the toggles are.
    if (sharedUI ? remoteNotificationBlocked : notificationsBlocked()) {
      const warn = clipCells(tr('permission.notify.blocked'), Math.max(0, Math.max(24, W - 11) - 22));
      out += ansi.moveTo(row, 21) + ansi.fg.red + warn + ansi.reset;
    }

    const btnCol = Math.max(24, W - 11);
    const btnHot = zone(row, btnCol, btnCol + displayWidth(tr('Reset')) + 3, 'reset-notify', { label: tr('Reset to default preset') });
    out += ansi.moveTo(row, btnCol) + button(tr('Reset'), btnHot, ansi.fg.cyan);
  }

  row = 7;
  for (let i = 0; i < NOTIFY_EVENTS.length; i++, row++) {
    const e = NOTIFY_EVENTS[i];
    const on = !!config.notify[e.key];
    const hot = zone(row, 3, Math.max(24, W - 2), `notify:${e.key}`,
      { label: tr('{action} {event} notification', { action: tr(on ? 'Disable' : 'Enable'), event: tr('event.' + e.key) }), tip: tr(e.desc) });
    const bg = hot ? ansi.bg.hover : '';
    out += ansi.moveTo(row, 3) + bg + chip(on ? MARK_ON : MARK_OFF, on, false);
    out += bg + (on ? ansi.reset + bg : ansi.dim + bg) + ' ' + padCells(tr('event.' + e.key), 19) + ansi.reset;
    out += bg + ansi.dim + tr(e.desc) + ansi.reset;
  }

  {
    const on = config.suppressDuringCompact;
    const hot = zone(row, 3, Math.max(24, W - 2), 'toggle-compact',
      { label: tr(on ? 'Allow notifications during compact' : 'Suppress notifications during compact'),
        tip: tr('Compaction fires Stop as a side effect') });
    const bg = hot ? ansi.bg.hover : '';
    out += ansi.moveTo(row, 3) + bg + chip(on ? MARK_ON : MARK_OFF, on, false);
    out += bg + (on ? ansi.reset + bg : ansi.dim + bg) + tr(' Suppress during compact') + ansi.reset;
    row++;
  }

  {
    const on = config.bookmarks;
    const hot = zone(row, 3, Math.max(24, W - 2), 'toggle-bookmarks',
      { label: tr(on ? 'Stop bookmarking terminals' : 'Bookmark terminals'),
        tip: tr('bookmark.tip') });
    const bg = hot ? ansi.bg.hover : '';
    out += ansi.moveTo(row, 3) + bg + chip(on ? MARK_ON : MARK_OFF, on, false);
    out += bg + (on ? ansi.reset + bg : ansi.dim + bg) + ' ' + tr('Bookmark in terminal') + ansi.reset;
    if (bookmarksUnavailable) {
      const why = tr(bookmarksUnavailable === 'unsupported' ? 'bookmark.unsupported' : 'bookmark.blocked');
      out += bg + ansi.dim + ansi.fg.red + '  ' + why + ansi.reset;
    }
    row++;
  }

  // ── Tracked terminals ──
  row++;
  const tracked = sm.getAll();
  out += ansi.moveTo(row, 2) + ansi.bold + tr('Terminals') + ansi.reset;
  if (tracked.length) {
    out += ansi.dim + `  (${tracked.length})` + ansi.reset;
  }
  if (badgesBlocked) {
    out += ansi.dim + ansi.fg.red + '  ' + clipCells(tr('permission.badge.blocked'), Math.max(0, W - 16)) + ansi.reset;
  }
  row++;
  if (tracked.length === 0) {
    out += ansi.moveTo(row, 3) + ansi.dim + tr('(none)') + ansi.reset;
    row++;
  } else {
    // Grow into the space available, but never starve the log completely.
    const budget = Math.max(2, H - row - 4);
    const shown = Math.min(tracked.length, Math.max(4, budget));
    for (let i = 0; i < shown; i++, row++) {
      const t = tracked[i];
      const icon = STATE_ICONS[t.state] || '?';
      const age = t.lastTransition ? `${Math.round((Date.now() - t.lastTransition) / 1000)}s` : '';
      const fg = STATE_FG[t.state] || ansi.fg.gray;
      const named = terminalInfo.has(t.id);
      // Names vary in length; pad them to a column so the states line up and
      // the panel can be read down rather than word by word.
      const nameW = Math.max(12, Math.min(22, Math.floor(W / 3)));
      const raw = terminalLabel(t.id, nameW) +
        (t.agent && t.agent !== 'claude' ? ` (${t.agent})` : '');
      const name = displayWidth(raw) > nameW ? clipCells(raw, nameW - 1) + '…' : padCells(raw, nameW);
      const hot = zone(row, 3, Math.max(24, W - 2), `clear-terminal:${t.id}`,
        { label: tr('Clear badge for {name}', { name: raw.trim() }),
          tip: named ? `T${t.id} · ${t.agent || '?'}` : tr('Right-click for terminal actions') });
      const bg = hot ? ansi.bg.hover : '';
      out += ansi.moveTo(row, 3) + bg + fg + icon + ' ' + name + ansi.reset;
      out += bg + ansi.dim + `  ${padCells(tr(t.state || 'null'), 10)}${age}` +
        (isCompacting(t.id) ? tr('  compacting') : '') + ansi.reset;
    }
    if (tracked.length > shown) {
      out += ansi.moveTo(row, 3) + ansi.dim + tr('+{count} more', { count: tracked.length - shown }) + ansi.reset;
      row++;
    }
  }

  // ── Log ──
  row++;
  const logHeaderRow = row;
  out += ansi.moveTo(row, 2) + ansi.bold + tr('Log') + ansi.reset;
  {
    const btnCol = Math.max(24, W - 11);
    const btnHot = zone(row, btnCol, btnCol + displayWidth(tr('Clear')) + 3, 'clear-log', { label: tr('Clear log') });
    out += ansi.moveTo(row, btnCol) + button(tr('Clear'), btnHot, ansi.fg.cyan);
  }
  row++;

  const logRows = Math.max(1, H - row + 1);
  const maxScroll = Math.max(0, log.length - logRows);
  if (logScroll > maxScroll) logScroll = maxScroll;
  for (let i = 0; i < logRows; i++) {
    const line = log[i + logScroll];
    if (line === undefined) break;
    zone(row + i, 1, W, 'log-area');
    out += ansi.moveTo(row + i, 3) + ansi.dim;
    out += displayWidth(line) > W - 4 ? clipCells(line, W - 7) + '...' : line;
    out += ansi.reset;
  }
  if (maxScroll > 0) {
    const pos = `${logScroll + 1}/${log.length - logRows + 1}`;
    out += ansi.moveTo(logHeaderRow, Math.max(6, W - 24)) + ansi.dim + pos + ansi.reset;
  }

  // Each positioned segment must fit the terminal, including translated text.
  out = out.replace(/\x1b\[(\d+);(\d+)H([\s\S]*?)(?=\x1b\[\d+;\d+H|$)/g,
    (_, r, c, text) => Number(r) + 2 - panelScroll > termRows || Number(r) + 2 - panelScroll < 3 || Number(c) > termCols ? '' :
      ansi.moveTo(Number(r) + 2 - panelScroll, c) + clipCells(text, termCols - Number(c) + 1) + ansi.reset);
  process.stdout.write(out);
  options.renderNavigation();
  syncPointer();
}

// Cursor shape and tooltip are host round-trips — only touch them when the
// hovered zone actually changes, otherwise every mouse motion fires two IPC calls.
function syncPointer() {
  const z = zoneAt(hoverRow, hoverCol);
  const wantCursor = (z && z.action !== 'log-area') ? 'pointer' : 'default';
  if (wantCursor !== appliedCursor) {
    appliedCursor = wantCursor;
    try { hecaton.window.set_cursor({ cursor: wantCursor }); } catch { /* optional API */ }
  }
  const wantTip = (z && z.tip) ? z.tip : '';
  if (wantTip !== appliedTooltip) {
    appliedTooltip = wantTip;
    try { hecaton.window.set_tooltip({ text: wantTip }); } catch { /* optional API */ }
  }
}

// ============================================================
// Input handler
// ============================================================
hecaton.on('window_resized', (params) => {
  termCols = params.cols || termCols;
  termRows = params.rows || termRows;
  rerender();
});
hecaton.on('locale_changed', (params) => {
  setUiLocale(params?.locale);
  appliedTooltip = null;
  rerender();
  if (sharedUI) return;
  for (const terminal of sm.getAll()) {
    const detail = terminal.model ? `${terminal.model} (${tr(terminal.state)})` : tr(terminal.state);
    setTerminalBadge(terminal.id, {
      label: `${STATE_ICONS[terminal.state] || '?'} ${terminal.agent || 'unknown'}`,
      icon: 'radio-tower', color: STATE_COLORS[terminal.state] || '#FFFFFF', detail });
  }
});
hecaton.on('ws_connected', (params) => {
  connections.set(params.connection_id, params.path);
  addLog(`Client connected: ${params.connection_id}`);
});
hecaton.on('ws_message_received', (params) => {
  onWsMessage(params);
});
hecaton.on('ws_disconnected', (params) => {
  connections.delete(params.connection_id);
  addLog(`Client disconnected: ${params.connection_id}`);
});
hecaton.on('http_request_received', (params) => {
  onHttpRequest(params);
});
hecaton.on('terminal_changed', (params) => {
  onTerminalChanged(params);
});
hecaton.on('dialog_resolved', (params) => {
  onDialogResult(params.button_id);
});
hecaton.on('window_minimized', () => {
  minimized = true;
  hoverRow = -1;
  hoverCol = -1;
  appliedTooltip = null;
  rerender();
});
hecaton.on('window_restored', () => {
  minimized = false;
  rerender();
});

// ============================================================
// Actions — every control resolves to one of these, whether it was
// clicked, picked from the context menu, or typed as a shortcut.
// ============================================================
async function runAction(action) {
  if (!action || action === 'log-area') return;
  const local = ['dashboard', 'install-hooks', 'open-log-file', 'quit'];
  if (sharedUI && !local.includes(action)) {
    if (serviceError && action === 'toggle-server') { await serviceRequest(); return; }
    await serviceRequest('action', { action });
    return;
  }
  if (options.service && local.includes(action)) return;
  if (action.startsWith('preset-set:')) {
    applyPreset(action.slice(11));
    await saveConfig(); rerender();
    return;
  }

  if (action.startsWith('notify:')) {
    const key = action.slice(7);
    const idx = NOTIFY_EVENTS.findIndex(e => e.key === key);
    if (idx === -1) return;
    toggleNotifyEvent(idx);
    await saveConfig();
    rerender();
    return;
  }

  if (action.startsWith('clear-terminal:')) {
    const id = parseInt(action.slice(15), 10);
    if (!Number.isFinite(id)) return;
    sm.remove(id);
    compacting.delete(id);
    setTerminalBadge(id, CLEAR_BADGE);
    addLog(`T${id} cleared`);
    return;
  }

  switch (action) {
    case 'dashboard': options.onBack(); break;
    case 'install-hooks': checkAndInjectHooks(); break;
    case 'toggle-server':
      if (serverRunning) await stopServer(); else await startServer();
      break;
    case 'toggle-pattern':
      if (patternEnabled) await stopPatternMatching(); else await startPatternMatching();
      break;
    case 'preset-next':
      cyclePreset(); await saveConfig(); rerender();
      break;
    case 'preset-prev': {
      const i = PRESET_ORDER.indexOf(config.preset);
      const prev = i <= 0 ? PRESET_ORDER[PRESET_ORDER.length - 1] : PRESET_ORDER[i - 1];
      applyPreset(prev); await saveConfig(); rerender();
      break;
    }
    case 'reset-notify':
      applyPreset(DEFAULT_CONFIG.preset);
      config.suppressDuringCompact = DEFAULT_CONFIG.suppressDuringCompact;
      config.bookmarks = DEFAULT_CONFIG.bookmarks;
      await saveConfig(); rerender();
      break;
    case 'toggle-compact':
      config.suppressDuringCompact = !config.suppressDuringCompact;
      await saveConfig(); rerender();
      break;
    case 'toggle-bookmarks':
      config.bookmarks = !config.bookmarks;
      await saveConfig(); rerender();
      break;
    case 'clear-log':
      log.length = 0; logScroll = 0; rerender();
      break;
    case 'open-log-file':
      if (logFilePath) hecaton.fs.reveal({ path: logFilePath }).catch(() => null);
      break;
    case 'quit':
      options.onClose();
      break;
  }
}

// ============================================================
// Mouse
// ============================================================
// Two delivery paths exist: precise events (overlay.precise_mouse) and raw SGR
// on stdin. Both are wired so the UI still works if the host declines one —
// once a precise event arrives, SGR is ignored to avoid double-handling.
let preciseMouseSeen = false;

function onMouseMove(row, col) {
  if (row === hoverRow && col === hoverCol) return;
  hoverRow = row;
  hoverCol = col;
  rerender();
}

function onMouseClick(row, col) {
  const z = zoneAt(row, col);
  if (z) runAction(z.action);
}

function onMouseScroll(deltaY) {
  const step = deltaY > 0 ? 3 : -3;
  if (termRows < 30) {
    const next = Math.max(0, Math.min(30 - termRows, panelScroll + step));
    if (next !== panelScroll) { panelScroll = next; rerender(); return; }
  }
  const next = Math.max(0, logScroll + step);
  if (next === logScroll) return;
  logScroll = next;
  rerender();
}

hecaton.on('mouse_event', (p) => {
  if (!preciseMouseSeen) addLog('Mouse: precise events active');
  preciseMouseSeen = true;
  const row = (p.cell_y || 0) + 1;
  const col = (p.cell_x || 0) + 1;
  if (p.type === 'motion') onMouseMove(row, col);
  else if (p.type === 'press' && (p.button || 0) === 0) onMouseClick(row, col);
  else if (p.type === 'scroll') onMouseScroll(p.scroll_delta_y || 0);
});

// Fallback: SGR sequences arriving on stdin. Returns true if input was mouse.
let sgrMouseSeen = false;

function handleMouseData(str) {
  if (preciseMouseSeen) return /\x1b\[</.test(str);
  const re = /\x1b\[<(\d+);(\d+);(\d+)([Mm])/g;
  let m, had = false;
  while ((m = re.exec(str)) !== null) {
    if (!sgrMouseSeen) { sgrMouseSeen = true; addLog('Mouse: SGR fallback active'); }
    had = true;
    const cb = parseInt(m[1], 10);
    const col = parseInt(m[2], 10);
    const row = parseInt(m[3], 10);
    const release = m[4] === 'm';
    if ((cb & 64) !== 0) onMouseScroll((cb & 1) !== 0 ? 1 : -1);
    else if ((cb & 32) !== 0) onMouseMove(row, col);
    else if (!release && (cb & 3) === 0) onMouseClick(row, col);
  }
  return had;
}

// ============================================================
// Context menu (right click)
// ============================================================
hecaton.on('menu_requested', (p) => {
  const row = p.row || 0;
  const col = p.col || 0;
  const z = zoneAt(row, col);
  const items = [{ id: 'dashboard', label: tr('Back to dashboard'), icon: 'home' },
    { id: 'install-hooks', label: tr('Install / update Claude Code hooks'), icon: 'settings' }];

  if (z && z.label && z.action !== 'log-area') {
    items.push({ id: z.action, label: z.label, icon: 'check' });
    items.push({ type: 'separator' });
  }

  items.push({
    id: 'toggle-server',
    label: serverRunning ? tr('Stop hook server') : tr('Start hook server'),
    icon: serverRunning ? 'debug-stop' : 'play',
  });
  items.push({
    id: 'toggle-pattern',
    label: patternEnabled ? tr('Stop pattern matching') : tr('Start pattern matching'),
    icon: 'search',
  });
  items.push({ type: 'separator' });

  items.push({
    id: 'notify-menu', label: tr('Notify'), icon: 'bell',
    children: [
      ...NOTIFY_EVENTS.map(e => ({
        id: `notify:${e.key}`, label: tr('event.' + e.key), checked: !!config.notify[e.key],
      })),
      { type: 'separator' },
      { id: 'toggle-compact', label: tr('Suppress during compact'), checked: config.suppressDuringCompact },
      { id: 'toggle-bookmarks', label: tr('Bookmark in terminal'), checked: config.bookmarks },
    ],
  });
  items.push({
    id: 'preset-menu', label: tr('Preset: {name}', { name: tr(config.preset) }), icon: 'settings',
    children: PRESET_ORDER.map(name => ({
      id: `preset-set:${name}`, label: tr(name), checked: config.preset === name,
    })),
  });
  items.push({ type: 'separator' });
  items.push({ id: 'clear-log', label: tr('Clear log'), icon: 'trash' });
  if (logFilePath) items.push({ id: 'open-log-file', label: tr('Reveal log file'), icon: 'go-to-file' });
  items.push({ type: 'separator' });
  items.push({ id: 'quit', label: tr('Quit'), icon: 'close' });

  hecaton.menu.show({ items });
});

hecaton.on('menu_activated', (p) => {
  const id = p.id || '';
  runAction(id);
});

function handleInput(data) {
  const str = data.toString();

  if (['\x1b[A', '\x1b[B', '\x1b[5~', '\x1b[6~'].includes(str)) {
    onMouseScroll(str === '\x1b[A' || str === '\x1b[5~' ? -1 : 1);
    return;
  }

  if (handleMouseData(str)) return;

  for (const ch of str) {
    switch (ch) {
      case 's':
        runAction('toggle-server');
        break;
      case 'p':
        runAction('toggle-pattern');
        break;
      case 'n':
        runAction('preset-next');
        break;
      case 'c':
        runAction('clear-log');
        break;
      case 'q':
        options.onClose();
        break;
    }
  }
  if (str === '\x1b') options.onBack();
}

// ============================================================
// WebSocket message handler
// ============================================================
function onWsMessage(params) {
  let data;
  try { data = JSON.parse(params.data); } catch { addLog(`Invalid JSON from ${params.connection_id}`); return; }
  processHookEvent(data);
}

// ============================================================
// HTTP request handler (POST /hook)
// ============================================================
// Only anomalies are logged here — processHookEvent already reports every
// event it accepts, and logging both doubled the log for no added information.
function onHttpRequest(params) {
  if (!params.body) {
    addLog(`HTTP ${params.method || '?'} ${params.path || '?'}: empty body`);
    return;
  }
  let data;
  try { data = JSON.parse(params.body); } catch { addLog('HTTP: invalid JSON body'); return; }
  processHookEvent(data);
}

// ============================================================
// Claude Code Hook Injection
// ============================================================
// PostToolUse is deliberately NOT registered: it fires once per tool call, and
// since the host never answers the request every one of those curls lingers for
// its full timeout. Its only benefit was clearing the `blocked` badge early —
// notifications already work without it, because Stop turns blocked into
// waiting, which is a real transition. processHookEvent still honours the event
// if something else sends it.
const HOOK_EVENTS = [
  { event: 'SessionStart', async: true },
  { event: 'UserPromptSubmit', async: true },
  { event: 'PermissionRequest', async: true },
  { event: 'Stop', async: true },
  { event: 'StopFailure', async: true },
  { event: 'PreCompact', async: true },
  { event: 'PostCompact', async: true },
  // Notification is matched on notification_type — only the idle one is useful here.
  { event: 'Notification', async: true, matcher: 'idle_prompt' },
  { event: 'SessionEnd', async: true },
];

const HOOK_MARKER = 'hecaton-agent-state';

// A live server answers (the host writes 200/404 itself), but a leaked one from
// a dead plugin accepts the connection and then never replies. Without
// --max-time those curls block forever, pile up, and starve the accept queue —
// at which point hooks stop arriving with no error anywhere. The timeout bounds
// that failure; the request is delivered long before it expires. `|| true` keeps
// a timeout (exit 28) from being reported as a failed hook.
function buildHookCommand(eventName) {
  return `curl -s -m 1 --connect-timeout 1 http://127.0.0.1:${PORT}/hook -d "{\\"client\\":\\"claude\\",\\"terminal_id\\":\\"$CONSOLE_TERMINAL_ID\\",\\"event\\":\\"${eventName}\\"}" > /dev/null 2>&1 || true`;
}

function expectedHookCommand(eventName) {
  return `${buildHookCommand(eventName)} # ${HOOK_MARKER}`;
}

function isOurHook(h) {
  return !!(h && h.command &&
    (h.command.includes(HOOK_MARKER) || h.command.includes(`127.0.0.1:${PORT}/hook`)));
}

// True only when our hook exists AND its command matches what this version
// emits, so a plugin upgrade rewrites stale commands instead of skipping them.
function hasCurrentHook(matcherArray, event, matcher = '') {
  if (!Array.isArray(matcherArray)) return false;
  const want = expectedHookCommand(event);
  for (const entry of matcherArray) {
    if ((entry.matcher || '') !== matcher) continue;
    for (const h of entry.hooks || []) {
      if (isOurHook(h)) return h.command === want;
    }
  }
  return false;
}

async function checkAndInjectHooks() {
  if (pendingDialogAction) return;
  try {
    const homeResult = await hecaton.env.get_home();
    const home = homeResult.path || homeResult.value || '';
    if (!home) { addLog('Cannot resolve home dir'); return; }

    const settingsPath = `${home}/.claude/settings.json`;

    let settings = {};
    try {
      const readResult = await hecaton.fs.read_file({ path: settingsPath });
      if (readResult && readResult.content) {
        settings = JSON.parse(readResult.content);
      }
    } catch (e) {
      addLog(`Cannot safely read Claude settings: ${e.message || e}`);
      return;
    }

    const hooks = settings.hooks || {};

    const stale = HOOK_EVENTS.filter(({ event, matcher }) => !hasCurrentHook(hooks[event], event, matcher || ''));

    if (stale.length === 0) {
      addLog('Claude Code hooks already up to date');
      return;
    }

    pendingDialogAction = 'hook_install';
    pendingSettingsPath = settingsPath;
    pendingSettings = settings;
    await hecaton.dialog.show({
      type: 'message',
      title: tr('Install Claude Code Hooks'),
      message: tr('Add or update hooks in Claude Code settings.json\nto enable Claude State detection.\n\nTarget: {path}\nOut of date: {events}', { path: settingsPath, events: stale.map(e => e.event).join(', ') }),
      buttons: [
        { id: 'install', label: tr('Install'), default: true, style: 'success' },
        { id: 'cancel', label: tr('Cancel') },
      ],
    });

  } catch (e) {
    pendingDialogAction = null;
    addLog(`Hook check error: ${e.message || e}`);
  }
}

let pendingDialogAction = null;
let pendingSettingsPath = null;
let pendingSettings = null;

async function onDialogResult(buttonId) {
  if (pendingDialogAction === 'hook_install') {
    pendingDialogAction = null;
    if (buttonId !== 'install') {
      addLog('Hook installation cancelled by user');
      return;
    }
    await performHookInstall();
  }
}

async function performHookInstall() {
  try {
    const settingsPath = pendingSettingsPath;
    if (!settingsPath) return;
    // The settings may have changed while the installation dialog was open.
    const latest = await hecaton.fs.read_file({ path: settingsPath });
    if (latest?.ok === false) throw new Error('Cannot read Claude settings; installation skipped');
    const settings = latest?.content ? JSON.parse(latest.content) : (pendingSettings || {});
    if (!settings || typeof settings !== 'object' || Array.isArray(settings)) {
      throw new Error('Claude settings must be a JSON object');
    }

    const hooks = settings.hooks || {};

    for (const { event, async: isAsync, matcher: wanted } of HOOK_EVENTS) {
      const targetMatcher = wanted || '';
      const hookEntry = {
        type: 'command',
        command: expectedHookCommand(event),
        async: isAsync,
      };

      if (!hooks[event]) hooks[event] = [];

      let matcherArr = hooks[event];
      if (!Array.isArray(matcherArr)) matcherArr = hooks[event] = [];

      let found = false;
      for (const entry of matcherArr) {
        if ((entry.matcher || '') === targetMatcher && Array.isArray(entry.hooks)) {
          const existing = entry.hooks.findIndex(isOurHook);
          if (existing === -1) entry.hooks.push(hookEntry);
          else entry.hooks[existing] = hookEntry;  // rewrite stale command in place
          found = true;
          break;
        }
      }

      if (!found) {
        matcherArr.push({ matcher: targetMatcher, hooks: [hookEntry] });
      }
    }

    // Drop our hooks from events we no longer register (e.g. after an upgrade
    // narrows the set), so retired events can't keep firing into a dead port.
    const active = new Set(HOOK_EVENTS.map(e => e.event));
    for (const event of Object.keys(hooks)) {
      if (active.has(event) || !Array.isArray(hooks[event])) continue;
      for (const entry of hooks[event]) {
        if (Array.isArray(entry.hooks)) entry.hooks = entry.hooks.filter(h => !isOurHook(h));
      }
      hooks[event] = hooks[event].filter(entry => (entry.hooks || []).length > 0);
      if (hooks[event].length === 0) delete hooks[event];
    }

    settings.hooks = hooks;

    const content = JSON.stringify(settings, null, 2);
    await hecaton.fs.write_file({ path: settingsPath, content });

    addLog(`Hooks installed to ${settingsPath}`);
    addLog(`${HOOK_EVENTS.length} events registered`);

    pendingSettings = null;
    pendingSettingsPath = null;
  } catch (e) {
    addLog(`Hook install error: ${e.message || e}`);
  }
}


// The dashboard owns stdin, rendering and process lifetime.
return {
  async start() {
    if (sharedUI) {
      await serviceRequest();
      if (!disposed && serverRunning) await checkAndInjectHooks();
      return;
    }
    for (const init of [initLogFile, loadConfig, refreshTerminalInfo, startServer]) {
      if (disposed) return;
      try { await init(); } catch (e) { addLog(`Initialization: ${e.message || e}`); }
    }
  },
  snapshot,
  action: runAction,
  show(value) {
    visible = value;
    if (value) panelScroll = 0;
    hoverRow = -1;
    hoverCol = -1;
    appliedTooltip = null;
    appliedCursor = null;
    if (visible) rerender();
  },
  render: rerender,
  input: handleInput,
  // Closing stdin prevents RPC replies, so issue all release requests before exit.
  async dispose() {
    if (disposed) return;
    disposed = true;
    clearTimeout(logFlushTimer);
    if (sharedUI) {
      if (serviceChannel) await serviceChannel.close();
      return;
    }
    const pending = [];
    const release = action => { try { pending.push(Promise.resolve(action()).catch(() => {})); } catch {} };
    if (serverId !== null) release(() => host.web.stop({ server_id: serverId }));
    if (subscriptionId !== null) release(() => host.terminal.unsubscribe({ subscription_id: subscriptionId }));
    for (const t of sm.getAll()) {
      release(() => host.terminal.set_status({ terminal_id: t.id, label: '', icon: '', color: '', detail: '' }));
    }
    await Promise.allSettled(pending);
  },
};
}

// One hook/state owner per plugin. Requests start it after a UI is attached so
// permission prompts have a window to target. Closing a UI only detaches it.
let serviceStart = null;
let serviceQueue = Promise.resolve();
let controller;
const serviceHost = hecaton.serviceHost({
  protocol: 1,
  onRequest: async (_link, method, params) => {
    if (!serviceStart) serviceStart = (async () => {
      await ensureNotificationPermission('permission.reason.startup');
      await controller.start();
    })();
    await serviceStart;
    const work = serviceQueue.then(async () => {
      if (method === 'action') await controller.action(params?.action);
      else if (method !== 'status') throw new Error('Unknown service request: ' + method);
      return controller.snapshot();
    });
    serviceQueue = work.catch(() => {});
    return work;
  },
});
controller = createClaudeState(hecaton, {
  service: true,
  onChange: (snapshot) => serviceHost.broadcast('state', snapshot).catch(() => {}),
});
hecaton.onShutdown(async () => {
  // Dispose now so a late serve/subscribe reply is released as well.
  await controller.dispose();
  await Promise.allSettled([serviceStart, serviceQueue]);
}, { graceMs: 4000 });
await serviceHost.listen();
