const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const dashboard = fs.readFileSync(path.join(root, 'src/dashboard.js'), 'utf8');
const state = fs.readFileSync(path.join(root, 'src/claude-state.js'), 'utf8');
// Hecaton runs a single script with top-level await; no module loader required.
const catalogs = Object.fromEntries(fs.readdirSync(path.join(root, 'locale')).filter(f => f.endsWith('.json')).sort()
  .map(file => [file.slice(0, -5), JSON.parse(fs.readFileSync(path.join(root, 'locale', file), 'utf8'))]));
const i18n = fs.readFileSync(path.join(root, 'src/i18n.js'), 'utf8');
const notifications = fs.readFileSync(path.join(root, 'src/notifications.js'), 'utf8');
const prefix = '#!/usr/bin/env node\n// Generated by scripts/build.cjs. Edit src/ and locale/.\n' +
  'const UI_CATALOGS = ' + JSON.stringify(catalogs, null, 2) + ';\n' + i18n + '\n' + notifications + '\n';
const outputs = {
  'main.js': prefix + dashboard.replace(/^#![^\n]*\n/, '') + '\n' + state,
  'service.js': prefix + state + '\n' + fs.readFileSync(path.join(root, 'src/service.js'), 'utf8'),
};
for (const [file, output] of Object.entries(outputs)) {
  if (process.argv.includes('--check')) {
    if (fs.readFileSync(path.join(root, file), 'utf8') !== output) throw new Error(file + ' is stale. Run node scripts/build.cjs');
  } else fs.writeFileSync(path.join(root, file), output);
}
